### ISSUE TITLE
你好，我按照方法引入报没找到依赖，组件注册什么的全做了，麻烦看看。

### ISSUE THREAD

**Issue by supuwoerc** [zhangxiaoshang/va-carousel#2]
This dependency was not found:

* va-carousel/src/components/VaCarousel in ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.5@babel-loader/lib!./node_modules/_cache
-loader@2.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.6.4@vue-loader/lib??vue-loader-options!./src/views/manager.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save va-carousel/src/components/VaCarousel

**Comment by zhangxiaoshang** [comment]
执行 `npm install --save va-carousel/src/components/VaCarousel`这句命令之后试试
